config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    put :check, on: :member
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :snapshots, through: :products

  validates :name, presence: true
  validates :products_count, numericality: { less_than: 9 }

  url_or_asin_is_blank = ->(att) { att[:url_or_asin].blank? }
  accepts_nested_attributes_for :products, allow_destroy: true,
                                           reject_if: url_or_asin_is_blank

  def build_empty_products
    (8 - products.size).times { products.build }
  end

  def products_count
    products.reject(&:marked_for_destruction?).size
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :group, counter_cache: true
  belongs_to :last_snapshot, class_name: 'Snapshot', optional: true
  has_many :snapshots, dependent: :destroy

  def url_or_asin
    url || asin
  end

  def url_or_asin=(url_or_asin)
    if url_or_asin.include?('/')
      self.url = url_or_asin
    else
      self.asin = url_or_asin
    end
  end

  def take_snapshot!
    snapshots.find_or_initialize_by(taken_on: Date.today).tap do |snap|
      snap.import_from(gateway)
      snap.transaction do
        snap.save!
        refresh_last_snapshot!
      end
    end
  end

  def gateway
    @gateway ||= AmazonProductGateway.new(self)
  end

  def refresh_last_snapshot!
    update!(last_snapshot: snapshots.order(:taken_on).last)
  end

  def safe_url
    return url if url.present?
    "https://www.amazon.com/dp/#{asin}"
  end

  def safe_asin
    return asin if asin.present?
    url[/\/(dp|product)\/(\w+)/, 2]
  end
end

app/models/snapshot.rb
class Snapshot < ApplicationRecord
  TRACKED_FIELDS = %i(title min_price max_price images features reviews_count
                      stock rank)
  ARRAY_FIELDS = %i(images features)

  belongs_to :product

  ARRAY_FIELDS.each { |field| serialize field, Array }

  def diff_to(other)
    SnapshotsComparator.new(self, other).as_hash
  end

  def import_from(source)
    Snapshot::TRACKED_FIELDS.each do |field|
      self[field] = source.public_send(field)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :can_track_competitors?

  private

  def can_track_competitors?
    Group.count < 10
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :allow_creation, only: %i(new create)
  before_action :set_group, only: %i(show edit update destroy check)

  def index
    @groups = Group.all
  end

  def show
  end

  def new
    @group = Group.new
    @group.build_empty_products
  end

  def edit
    @group.build_empty_products
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html do
          redirect_to action: :index, notice: 'Group was successfully created.'
        end
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html do
          redirect_to @group, notice: 'Group was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html do
        redirect_to groups_url, notice: 'Group was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def check
    unless Rails.env.development?
      redirect_to root_path
      return
    end

    SnapshotTakerJob.perform_later(@group.id)
    redirect_to groups_path, notice: 'Check started'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(
      :name, products_attributes: %i(id url_or_asin _destroy)
    )
  end

  def allow_creation
    return if can_track_competitors?
    redirect_to(action: :index)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'control-label' %>
    <%= form.text_field :name, id: 'group_name', class: 'form-control' %>
  </div>

  <hr>

  <%= form.fields_for :products do |pf, idx| %>
    <div class="form-group">
      <%= pf.label :url_or_asin, "Product ##{pf.index + 1}", class: 'control-label' %>
      <%= pf.text_field :url_or_asin, class: 'form-control', readonly: pf.object.persisted?,
                                      placeholder: 'URL or ASIN' %>
    </div>
  <% end %>

  <div class="form-group actions">
    <%= form.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', groups_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups of Competitors</h1>
<p class="text-muted">You can track up to 10 groups!</p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Group</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group %></td>
        <td><%= group.products_count %> <%= Product.model_name.human.pluralize(group.products_count).downcase %></td>
        <td class="text-right">
          <% if Rails.env.development? %>
            <%= link_to 'Run Check', check_group_path(group), method: :put, class: 'btn btn-link btn-xs' %>
          <% end %>

          <%= link_to edit_group_path(group), class: 'btn btn-warning btn-xs' do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>

          <%= link_to group, method: :delete, data: { confirm: 'Are you sure?' },
                             class: 'btn btn-danger btn-xs' do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can_track_competitors? %>
  <%= link_to new_group_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Track my Competitors
  <% end %>
<% end %>

app/views/groups/new.html.erb
<h1>Add Group of Competitors</h1>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @group.name %></h1>
<p class="text-muted"><%= @group.products_count %> products</p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Product</th>
      <th>Stock</th>
      <th>Price</th>
      <th>Reviews</th>
    </tr>
  </thead>

  <tbody>
    <% @group.products.preload(:last_snapshot).each do |product| %>
      <tr>
        <td>
          <%= link_to (product.last_snapshot&.title || product.safe_url), product.safe_url %>
        </td>
        <td><%= product.last_snapshot&.stock %></td>
        <td>
          <% if product.last_snapshot %>
            <%= number_to_currency product.last_snapshot.min_price || 0 %>

            <% if product.last_snapshot.max_price != product.last_snapshot.min_price %>
              - <%= number_to_currency product.last_snapshot.max_price || 0 %>
            <% end %>
          <% end %>
        </td>
        <td><%= product.last_snapshot&.reviews_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_group_path(@group), class: 'btn btn-warning' %>
<%= link_to 'Back', groups_path, class: 'btn btn-link' %>

app/views/home/index.html.erb
<h1 class="text-center">Welcome to Cash Cow Pro</h1>
<p class="text-center text-muted">Monitor your competitors and find out how to beat them!</p>

<br>
<br>

<div class="row">
  <div class="col-sm-3"></div>

  <% if can_track_competitors? %>
    <div class="col-sm-3 text-center">
      <%= link_to 'Track my Competitors', new_group_path %>
    </div>
  <% end %>

  <% if Group.any? %>
    <div class="col-sm-3 text-center">
      <%= link_to 'See my Groups', groups_path %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cash Cow Pro | Test App</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default" role="navigation">
      <div class="container container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
            <span class="sr-only">Menu</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'CCP - Test App', root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'My Groups', groups_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>